import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import cp from 'node:child_process';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { verify,human,SLOT_NAMES } from './verify-runtime-parity.mjs';
import { readStrictJson,parseStrictJsonText } from './strict-json.mjs';

const here=path.dirname(fileURLToPath(import.meta.url));const projectRoot=path.resolve(here,'../..');
const write=(p,s,mode)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s);if(mode!==undefined)fs.chmodSync(p,mode);};
const git=(root,args)=>cp.execFileSync('git',args,{cwd:root,stdio:'ignore'});
const capsule=(id)=>({$schema:'../schemas/capsule.schema.json',schemaVersion:'1.1.0',status:'characterization',identity:{id,displayName:id,role:'fixture'},personalityRef:`personality/${id}.yaml`,skills:[],capabilityPacks:{requested:[],inactive:[]},routingPreferences:[],modelDefaults:{providerRef:'fixture',model:'fixture'},memoryNamespace:id,branding:{themeRef:'tui/skin.yaml',icon:'x',welcomeRef:`personality/${id}.yaml`},completion:{criteriaRefs:[],reportFormatRefs:[]}});
function fixture(){
  const top=fs.mkdtempSync(path.join(os.tmpdir(),'trio-001c-hostile-'));const governance=path.join(top,'governance');fs.mkdirSync(governance);fs.cpSync(path.join(projectRoot,'trio/governance/schemas'),path.join(governance,'schemas'),{recursive:true});
  const manifest=structuredClone(readStrictJson(path.join(projectRoot,'trio/governance/boundary-manifest.json')));const manifestPath=path.join(governance,'boundary-manifest.json');
  // The fixture builds its own minimal world, so it does not inherit owner-scoped rules
  // for trees it never creates: an acknowledged tree digest must be checked against the
  // tree it was measured from, and inheriting the declaration without the bytes would
  // force the check to be softened for everyone. ownerScopedTree() adds one deliberately.
  manifest.rules=manifest.rules.filter((r)=>r.class!=='owner-scoped-asset');
  const slots={};for(const slot of SLOT_NAMES){const root=path.join(top,slot);slots[slot]=root;fs.mkdirSync(root);const spec=manifest.repositories[slot];
    write(path.join(root,'package.json'),JSON.stringify({name:spec.packageNames['package.json'],description:slot,version:'0.0.0',type:'module',private:true,scripts:{start:'node dist/index.js'},dependencies:{alpha:'1.0.0'},devDependencies:{test:'1.0.0'}}));
    write(path.join(root,'tui/package.json'),JSON.stringify({name:spec.packageNames['tui/package.json'],version:'0.0.0',type:'module',private:true,scripts:{start:'node src/server.ts'}}));
    write(path.join(root,'src/main.ts'),'export const value=1;\n');
    for(const [agent,id] of [['pehlichi','pehlichi'],['loony-luna','luna'],['mad-ptah','ptah']])write(path.join(root,`trio/governance/capsules/${agent}.json`),JSON.stringify(capsule(id)));
    // The verifier binds to the Truth release the activation wrapper executes and checks
    // each repository's own pin against it, so a fixture world needs that pin to exist.
    fs.cpSync(path.join(projectRoot,'trio/runtime-closure.json'),path.join(root,'trio/runtime-closure.json'));
    git(root,['init','-q']);git(root,['config','user.email','fixture@example.invalid']);git(root,['config','user.name','fixture']);git(root,['remote','add','origin',`https://github.com/RootZ3n/${slot}.git`]);
  }
  function setManifest(value,text=null){const data=text??JSON.stringify(value);write(manifestPath,data);for(const root of Object.values(slots))write(path.join(root,'trio/governance/boundary-manifest.json'),data);}
  setManifest(manifest);
  const inventory={schemaVersion:'1.0.0',status:'characterization',rules:{}};const excluded=(rel)=>manifest.exclusions.some((x)=>rel===x.path||rel.startsWith(x.path+'/'));const union=new Set();for(const root of Object.values(slots)){const visit=(dir,base='')=>{for(const ent of fs.readdirSync(dir,{withFileTypes:true})){const rel=base?`${base}/${ent.name}`:ent.name;if(excluded(rel))continue;if(ent.isDirectory())visit(path.join(dir,ent.name),rel);else union.add(rel);}};visit(root);}for(const rule of manifest.rules.filter((x)=>x.selector.directory)){const s=rule.selector;inventory.rules[rule.id]=[...union].filter((rel)=>rel.startsWith(s.directory+'/')&&!(s.excludedPaths??[]).includes(rel)&&!(s.excludedDirectories??[]).some((d)=>rel===d||rel.startsWith(d+'/'))&&(!s.allowedSuffixes||s.allowedSuffixes.some((x)=>rel.endsWith(x)))).sort();}
  if(inventory.rules['trio-scaffolding']&&!inventory.rules['trio-scaffolding'].includes('trio/governance/path-inventory.json'))inventory.rules['trio-scaffolding'].push('trio/governance/path-inventory.json');
  const inventoryPath=path.join(governance,'path-inventory.json');const setInventory=(value)=>{write(inventoryPath,JSON.stringify(value));for(const root of Object.values(slots))write(path.join(root,'trio/governance/path-inventory.json'),JSON.stringify(value));};setInventory(inventory);
  for(const root of Object.values(slots)){git(root,['add','.']);git(root,['commit','-qm','fixture']);}
  return {top,governance,manifest,manifestPath,inventory,inventoryPath,slots,setManifest,setInventory};
}

/**
 * Install one owner-scoped tree into the fixture and acknowledge its measured digest.
 *
 * `mutate` runs after the files are written and before the digest is taken, so a test can
 * choose whether the acknowledgement matches the bytes on disk.
 */
function ownerScopedTree(f,{owner='loony-luna',dir='luna-private',files={'notes.md':'# private\n','asset.txt':'inert\n'},rule={},acknowledge=true}={}){
  for(const [rel,body] of Object.entries(files))write(path.join(f.slots[owner],dir,rel),body);
  const members=Object.keys(files).map((r)=>`${dir}/${r}`).sort((a,b)=>Buffer.from(a).compare(Buffer.from(b)));
  const hash=crypto.createHash('sha256');
  for(const rel of members){const bytes=fs.readFileSync(path.join(f.slots[owner],rel));hash.update(`file:${Buffer.byteLength(rel)}:`).update(rel).update(`:${bytes.length}:`).update(bytes);}
  const measured=`sha256:${hash.digest('hex')}`;
  f.manifest.rules.push({id:'owner-scoped-fixture',selector:{directory:dir,closedInventory:true},class:'owner-scoped-asset',owner,
    attestation:'Fixture-owned private tree, unreachable from the shared runtime.',
    ownerTreeDigest:acknowledge?measured:'sha256:'+'0'.repeat(64),
    bytesMustMatch:false,modeMustMatch:true,allowedTypes:['file'],permittedFormats:['markdown','data'],
    validation:{kind:'none'},productionReachable:false,divergenceBlocking:false,transitional:false,expiresBefore:null,...rule});
  f.setManifest(f.manifest);
  f.inventory.rules['owner-scoped-fixture']=members;
  f.setInventory(f.inventory);
  return {members,measured,dir,owner};
}

const clean=(f)=>fs.rmSync(f.top,{recursive:true,force:true});const run=(f)=>verify({slots:f.slots,manifestPath:f.manifestPath});
const ERROR_STATUSES=new Set(['SCHEMA_INVALID','MANIFEST_INVALID','MANIFEST_DIVERGENCE','IDENTITY_INVALID','JSON_INVALID','MISSING_INPUT','INVALID_INPUT']);
const expectBlocked=(r,klass,status='VERIFIER_OK_DIVERGENCE')=>{assert.equal(r.status,status);assert.equal(r.summary.verdict,status==='VERIFIER_OK_DIVERGENCE'?'BLOCKING_DIVERGENCE':'VERIFIER_ERROR');assert.notEqual(r.summary.verdict,'PARITY');if(klass)assert.ok(r.failures.some((x)=>x.failureClass===klass),`${klass} absent; got ${r.failures.map((x)=>x.failureClass)}`);if(status!=='VERIFIER_OK_DIVERGENCE')assert.ok(ERROR_STATUSES.has(status));};
const expectFinding=(r,{failureClass,agent=null,affectedPath,status='VERIFIER_OK_DIVERGENCE'})=>{expectBlocked(r,failureClass,status);assert.ok(r.failures.some((x)=>x.failureClass===failureClass&&x.agent===agent&&x.affectedPath===affectedPath),`${failureClass} with agent=${agent} path=${affectedPath} absent`);};
function divergentFile(f,rel,common='same',changed='different',mode){for(const root of Object.values(f.slots))write(path.join(root,rel),common,mode);write(path.join(f.slots['loony-luna'],rel),changed,mode);}

test('closed fixture can reach parity only with three valid, unique labeled identities',()=>{const f=fixture();try{assert.equal(run(f).summary.verdict,'PARITY');}finally{clean(f);}});
for(const [label,rel] of Object.entries({capsule:'trio/governance/capsules/overlay.js',branding:'ui/brand.js',deployment:'deploy/launch.sh',generated:'dist/entry.js',fixture:'fixtures/run.js',compatibility:'compatibility/run.js',UI:'ui/worker.js',skill:'skills/handler.ts',obsolete:'server.py'}))test(`hostile: executable divergence under ${label} cannot be variable or ignored`,()=>{const f=fixture();try{divergentFile(f,rel,'export default 1','export default 2');expectBlocked(run(f));}finally{clean(f);}});
test('hostile: package behavior projection blocks scripts, exports, imports, dependencies, and resolutions',()=>{const f=fixture();try{const p=structuredClone(readStrictJson(path.join(f.slots['loony-luna'],'package.json')));Object.assign(p,{scripts:{start:'evil'},exports:{'.':'./evil.js'},imports:{'#x':'./evil.js'},dependencies:{alpha:'9.0.0'},resolutions:{alpha:'9.0.0'}});write(path.join(f.slots['loony-luna'],'package.json'),JSON.stringify(p));expectBlocked(run(f),'BEHAVIOR_DIVERGENCE');}finally{clean(f);}});
test('hostile: every declared package behavioral projection field changes its digest',()=>{const baseline=structuredClone(readStrictJson(path.join(projectRoot,'trio/governance/boundary-manifest.json')));const strings=new Set(['version','type','main','module','types','browser','packageManager']);const booleans=new Set(['private','sideEffects','preferGlobal','gypfile']);const arrays=new Set(['files','os','cpu','libc','man','bundleDependencies','bundledDependencies']);for(const field of baseline.packageBehaviorFields){const f=fixture();try{const p=structuredClone(readStrictJson(path.join(f.slots['loony-luna'],'package.json')));p[field]=strings.has(field)?`changed-${field}`:booleans.has(field)?!Boolean(p[field]):arrays.has(field)?[`changed-${field}`]:{changed:field};write(path.join(f.slots['loony-luna'],'package.json'),JSON.stringify(p));expectFinding(run(f),{failureClass:'BEHAVIOR_DIVERGENCE',affectedPath:'package.json'});}finally{clean(f);}}});
test('hostile: package name/description metadata is identity-bound or inert as declared',()=>{const f=fixture();try{const p=structuredClone(readStrictJson(path.join(f.slots['loony-luna'],'package.json')));p.description='safe inert description';write(path.join(f.slots['loony-luna'],'package.json'),JSON.stringify(p));assert.equal(run(f).summary.verdict,'PARITY');p.name='pehlichi';write(path.join(f.slots['loony-luna'],'package.json'),JSON.stringify(p));expectBlocked(run(f),'PACKAGE_IDENTITY_MISMATCH','IDENTITY_INVALID');}finally{clean(f);}});
test('hostile: service units, inline scripts, workers, and alternate launchers block',()=>{const f=fixture();try{divergentFile(f,'agent.service','[Service]\nExecStart=/bin/true','[Service]\nExecStart=/bin/evil');divergentFile(f,'ui/index.html','<script>one()</script>','<script>two()</script>');divergentFile(f,'tui/test.sh','#!/bin/sh\ntrue','#!/bin/sh\nevil',0o755);expectBlocked(run(f));}finally{clean(f);}});
test('hostile: compiled entry point and executable profile overlay block',()=>{const f=fixture();try{divergentFile(f,'dist/index.js','export default 1','export default 2');write(path.join(f.slots.pehlichi,'src/profiles/agent.ts'),'export const id=1');write(path.join(f.slots['loony-luna'],'src/profiles/agent.ts'),'export const id=2');write(path.join(f.slots['mad-ptah'],'src/profiles/agent.ts'),'export const id=1');expectBlocked(run(f),'UNCLASSIFIED_FILE');}finally{clean(f);}});
test('identity: duplicate canonical realpaths and symlink aliases are rejected',()=>{const f=fixture();try{f.slots['loony-luna']=f.slots.pehlichi;expectBlocked(run(f),'DUPLICATE_REPOSITORY','IDENTITY_INVALID');const alias=path.join(f.top,'alias');fs.symlinkSync(f.slots.pehlichi,alias);f.slots['loony-luna']=alias;expectBlocked(run(f),'DUPLICATE_REPOSITORY','IDENTITY_INVALID');}finally{clean(f);}});
test('identity: swapped labels, remote mismatches, and package mismatches reject',()=>{const f=fixture();try{[f.slots.pehlichi,f.slots['loony-luna']]=[f.slots['loony-luna'],f.slots.pehlichi];expectBlocked(run(f),'REPOSITORY_NAME_MISMATCH','IDENTITY_INVALID');}finally{clean(f);}});
test('identity: missing repository produces structured failure',()=>{const f=fixture();try{f.slots['mad-ptah']=path.join(f.top,'missing');expectBlocked(run(f),'MALFORMED_REPOSITORY','IDENTITY_INVALID');}finally{clean(f);}});
test('rules: duplicate and overlapping domains reject before scanning',()=>{const f=fixture();try{f.manifest.rules.push({...f.manifest.rules.find((x)=>x.id==='source-runtime')});f.setManifest(f.manifest);const r=run(f);expectBlocked(r,'DUPLICATE_RULE','MANIFEST_INVALID');expectBlocked(r,'AMBIGUOUS_RULES','MANIFEST_INVALID');}finally{clean(f);}});
test('rules: different repository-local classifications are rejected',()=>{const f=fixture();try{const local=structuredClone(readStrictJson(path.join(f.slots['loony-luna'],'trio/governance/boundary-manifest.json')));local.rules.find((x)=>x.id==='source-runtime').class='quarantined-blocking-divergence';write(path.join(f.slots['loony-luna'],'trio/governance/boundary-manifest.json'),JSON.stringify(local));expectBlocked(run(f),'MANIFEST_DIVERGENCE','MANIFEST_DIVERGENCE');}finally{clean(f);}});
// The injection is asserted, not assumed. The previous form of this test rewrote a literal
// that the manifest no longer contained, so it silently shipped a *valid* document and then
// congratulated the verifier for accepting it. A fixture that can no-op proves nothing.
test('strict JSON: duplicate keys reject before JSON parsing can discard evidence',()=>{const f=fixture();try{const body=JSON.stringify(f.manifest);const text=`{"schemaVersion":"9.9.9",${body.slice(1)}`;assert.throws(()=>parseStrictJsonText(text),(e)=>e.code==='JSON_DUPLICATE_KEY','fixture failed to inject a detectable duplicate key');assert.equal(JSON.parse(text).schemaVersion,f.manifest.schemaVersion,'a permissive parser must silently discard the decoy, or this test proves nothing');f.setManifest(f.manifest,text);expectBlocked(run(f),'SCHEMA_VALIDATION','SCHEMA_INVALID');}finally{clean(f);}});
test('schemas: invalid boundary and unsupported versions reject',()=>{const f=fixture();try{f.manifest.schemaVersion='999.0.0';f.manifest.unknown=true;f.setManifest(f.manifest);expectBlocked(run(f),'SCHEMA_VALIDATION','SCHEMA_INVALID');}finally{clean(f);}});
test('schemas: invalid capsule, capability-pack, deployment, and runtime instances block',()=>{const f=fixture();try{const badCapsule={...capsule('luna'),authorityGrant:'root'};write(path.join(f.slots['loony-luna'],'trio/governance/capsules/loony-luna.json'),JSON.stringify(badCapsule));for(const root of Object.values(f.slots)){write(path.join(root,'trio/governance/capability-packs/bad.json'),'{"schemaVersion":"999"}');write(path.join(root,'trio/deployment/bad.json'),'{"schemaVersion":"1.0.0","plaintextCredential":"secret"}');write(path.join(root,'trio/governance/runtime-manifest.characterization.json'),'{"schemaVersion":"1.0.0","trusted":true}');}expectBlocked(run(f),'CAPSULE_IDENTITY_MISMATCH','IDENTITY_INVALID');}finally{clean(f);}});
test('strict JSON: oversized, deeply nested, long-string, and oversized-collection inputs reject',()=>{const f=fixture();try{write(f.manifestPath,' '.repeat(1_048_577));expectBlocked(run(f),'SCHEMA_VALIDATION','SCHEMA_INVALID');f.setManifest(f.manifest);const p=path.join(f.slots.pehlichi,'trio/governance/capsules/pehlichi.json');write(p,'['.repeat(40)+'0'+']'.repeat(40));expectBlocked(run(f),'CAPSULE_IDENTITY_MISMATCH','IDENTITY_INVALID');}finally{clean(f);}});
for(const [label,bad] of [['absolute','/tmp/x'],['parent','a/../x'],['dot','a/./x'],['repeated','a//x'],['control','a/\u0001x'],['trailing-space','a/x '],['trailing-dot','a/x.'],['case-confusable','SRC'],['unicode-confusable','src/main．js']])test(`paths: ${label} selector rejects`,()=>{const f=fixture();try{f.manifest.rules.push({...f.manifest.rules[0],id:`bad-${label}`,selector:{paths:[bad]}});f.setManifest(f.manifest);expectBlocked(run(f),undefined,label==='control'?'SCHEMA_INVALID':'MANIFEST_INVALID');}finally{clean(f);}});
test('mode-only behavior change blocks',()=>{const f=fixture();try{fs.chmodSync(path.join(f.slots['loony-luna'],'src/main.ts'),0o755);expectBlocked(run(f),'BEHAVIOR_DIVERGENCE');}finally{clean(f);}});
for(const target of ['inside','outside','sibling','cycle'])test(`symlink policy rejects ${target} link`,()=>{const f=fixture();try{const link=path.join(f.slots['loony-luna'],'src/link.ts');let value='main.ts';if(target==='outside'){value=path.join(f.top,'outside');write(value,'x');}if(target==='sibling')value=path.join(f.slots.pehlichi,'src/main.ts');if(target==='cycle')value='link.ts';fs.symlinkSync(value,link);expectBlocked(run(f),'SYMLINK_REJECTED');}finally{clean(f);}});
test('generated/runtime disguise and changed compiled output block',()=>{const f=fixture();try{divergentFile(f,'dist/runtime.js','export default 1','export default 2');expectBlocked(run(f),'UNCLASSIFIED_FILE');f.manifest.rules.find((x)=>x.id==='source-runtime').class='documentation';f.setManifest(f.manifest);expectBlocked(run(f),undefined,'MANIFEST_INVALID');}finally{clean(f);}});
test('untracked and git-ignored executables are still scanned and block',()=>{const f=fixture();try{for(const root of Object.values(f.slots))write(path.join(root,'.gitignore'),'ignored/\n');write(path.join(f.slots['loony-luna'],'ignored/run.sh'),'#!/bin/sh\nevil\n',0o755);write(path.join(f.slots.pehlichi,'mystery.js'),'evil()');expectBlocked(run(f),'UNCLASSIFIED_FILE');}finally{clean(f);}});
test('unsafe arbitrary exclusion cannot disguise ignored executable behavior',()=>{const f=fixture();try{f.manifest.exclusions.push({path:'ignored',kind:'cache-tree',attestation:'fake ignored tree'});f.setManifest(f.manifest);expectBlocked(run(f),'UNATTESTED_EXCLUSION','MANIFEST_INVALID');}finally{clean(f);}});
test('lockfile and package-manager configuration changes block',()=>{const f=fixture();try{divergentFile(f,'pnpm-lock.yaml','lockfileVersion: 9\n','lockfileVersion: 9\npackages: {evil: true}\n');divergentFile(f,'pnpm-workspace.yaml','packages: []\n','packages: [evil]\n');expectBlocked(run(f),'BEHAVIOR_DIVERGENCE');}finally{clean(f);}});
test('manifest rule reordering is semantically identical',()=>{const f=fixture();try{const before=run(f);f.manifest.rules.reverse();f.setManifest(f.manifest);const after=run(f);assert.equal(before.summary.verdict,'PARITY');assert.equal(after.summary.verdict,'PARITY');assert.equal(before.boundaryManifest.digest,after.boundaryManifest.digest);assert.deepEqual(before.summary,after.summary);}finally{clean(f);}});
test('safe validated capsule data change is reported without false runtime divergence',()=>{const f=fixture();try{const p=path.join(f.slots['loony-luna'],'trio/governance/capsules/loony-luna.json');const value=structuredClone(readStrictJson(p));value.branding.icon='moon';write(p,JSON.stringify(value));const r=run(f);assert.equal(r.status,'VERIFIER_OK_PARITY');assert.equal(r.summary.verdict,'PARITY');assert.ok(r.variableDifferences.some((x)=>x.path==='trio/governance/capsules/loony-luna.json'));assert.equal(r.repositoryIdentities.find((x)=>x.agent==='loony-luna').dirtyStateVisible,true);}finally{clean(f);}});
test('unexpected working directory still produces a structured invalid-input result',()=>{const f=fixture();const prior=process.cwd();try{process.chdir(f.top);const body=verify({slots:{},manifestPath:f.manifestPath});assert.equal(body.status,'IDENTITY_INVALID');assert.equal(body.summary.verdict,'VERIFIER_ERROR');assert.ok(body.failures.every((x)=>x.failureClass==='MISSING_REPOSITORY'));}finally{process.chdir(prior);clean(f);}});

test('TRIO-001D regression: prototype schema input is a precise structured rejection, never green parity',()=>{const f=fixture();try{const normal=capsule('luna');write(path.join(f.slots['loony-luna'],'trio/governance/capsules/loony-luna.json'),`{"__proto__":${JSON.stringify(normal)}}`);expectFinding(run(f),{failureClass:'CAPSULE_IDENTITY_MISMATCH',agent:'loony-luna',affectedPath:'trio/governance/capsules/loony-luna.json',status:'IDENTITY_INVALID'});}finally{clean(f);}});
test('TRIO-001D regression: capsule mode mismatch blocks with exact path',()=>{const f=fixture();try{fs.chmodSync(path.join(f.slots['loony-luna'],'trio/governance/capsules/loony-luna.json'),0o600);expectFinding(run(f),{failureClass:'VARIABLE_MODE_MISMATCH',affectedPath:'trio/governance/capsules/loony-luna.json'});}finally{clean(f);}});
test('TRIO-001D regression: newly inherited active Markdown is unclassified and blocking',()=>{const f=fixture();try{write(path.join(f.slots['loony-luna'],'docs/new-active.md'),'<script>attack()</script>');expectFinding(run(f),{failureClass:'UNCLASSIFIED_FILE',agent:'loony-luna',affectedPath:'docs/new-active.md'});}finally{clean(f);}});
test('TRIO-001D regression: .next server and browser output cannot hide',()=>{const f=fixture();try{write(path.join(f.slots['loony-luna'],'.next/server/route.js'),'attack()');write(path.join(f.slots['mad-ptah'],'.next/static/browser.js'),'attack()');expectFinding(run(f),{failureClass:'UNCLASSIFIED_FILE',agent:'loony-luna',affectedPath:'.next/server/route.js'});expectFinding(run(f),{failureClass:'UNCLASSIFIED_FILE',agent:'mad-ptah',affectedPath:'.next/static/browser.js'});}finally{clean(f);}});
test('TRIO-001D regression: coverage browser JavaScript cannot hide',()=>{const f=fixture();try{write(path.join(f.slots.pehlichi,'coverage/browser.js'),'attack()');expectFinding(run(f),{failureClass:'UNCLASSIFIED_FILE',agent:'pehlichi',affectedPath:'coverage/browser.js'});}finally{clean(f);}});
test('TRIO-001D regression: PNG-signature polyglot is invalid and quarantined',()=>{const f=fixture();try{const sig=Buffer.from([137,80,78,71,13,10,26,10]);for(const root of Object.values(f.slots))write(path.join(root,'peh-hedge-knight.png'),Buffer.concat([sig,Buffer.from('<script>attack()</script>')]));expectFinding(run(f),{failureClass:'CONTENT_VALIDATION',agent:'pehlichi',affectedPath:'peh-hedge-knight.png'});expectFinding(run(f),{failureClass:'QUARANTINED_DIVERGENCE',affectedPath:'peh-hedge-knight.png'});}finally{clean(f);}});

test('TRIO-001D variable contract: executable bit, absence, directory, and symlink substitutions block',()=>{const f=fixture();try{const target='trio/governance/capsules/pehlichi.json';fs.chmodSync(path.join(f.slots['loony-luna'],target),0o755);expectFinding(run(f),{failureClass:'VARIABLE_MODE_MISMATCH',affectedPath:target});fs.chmodSync(path.join(f.slots['loony-luna'],target),0o644);fs.unlinkSync(path.join(f.slots['loony-luna'],target));expectFinding(run(f),{failureClass:'VARIABLE_PRESENCE_MISMATCH',affectedPath:target});fs.mkdirSync(path.join(f.slots['loony-luna'],target));expectFinding(run(f),{failureClass:'VARIABLE_FILE_TYPE',agent:'loony-luna',affectedPath:target});fs.rmSync(path.join(f.slots['loony-luna'],target),{recursive:true});fs.symlinkSync('loony-luna.json',path.join(f.slots['loony-luna'],target));expectFinding(run(f),{failureClass:'SYMLINK_REJECTED',agent:'loony-luna',affectedPath:target});}finally{clean(f);}});
test('TRIO-001D variable contract: 0644 versus 0600 and empty versus absent are visible blockers',()=>{const f=fixture();try{const target='trio/governance/capsules/pehlichi.json';fs.chmodSync(path.join(f.slots['loony-luna'],target),0o600);expectFinding(run(f),{failureClass:'VARIABLE_MODE_MISMATCH',affectedPath:target});write(path.join(f.slots['loony-luna'],target),'');expectFinding(run(f),{failureClass:'CONTENT_VALIDATION',agent:'loony-luna',affectedPath:target});fs.unlinkSync(path.join(f.slots['loony-luna'],target));expectFinding(run(f),{failureClass:'VARIABLE_PRESENCE_MISMATCH',affectedPath:target});}finally{clean(f);}});
test('TRIO-001D variable contract: hard links are rejected and optionality cannot be invented ad hoc',()=>{const f=fixture();try{const target='trio/governance/capsules/pehlichi.json',selected=path.join(f.slots['loony-luna'],'trio/governance/capsules/loony-luna.json');fs.unlinkSync(path.join(f.slots['loony-luna'],target));fs.linkSync(selected,path.join(f.slots['loony-luna'],target));expectFinding(run(f),{failureClass:'HARDLINK_REJECTED',agent:'loony-luna',affectedPath:target});const rule=f.manifest.rules.find((x)=>x.id==='capsule-data');rule.optionalPaths=[target];f.setManifest(f.manifest);expectBlocked(run(f),'SCHEMA_VALIDATION','SCHEMA_INVALID');}finally{clean(f);}});
test('TRIO-001D closed inventory detects an inventoried common file deleted from all repositories',()=>{const f=fixture();try{for(const root of Object.values(f.slots))fs.unlinkSync(path.join(root,'src/main.ts'));expectFinding(run(f),{failureClass:'MISSING_BEHAVIOR_FILE',affectedPath:'src/main.ts'});}finally{clean(f);}});
test('TRIO-001D identity envelope binds unclassified bytes and blocking state',()=>{const f=fixture();try{const before=run(f),prior=before.repositoryIdentities.find((x)=>x.agent==='loony-luna');write(path.join(f.slots['loony-luna'],'new-cache/attack.js'),'attack-one()');const first=run(f),a=first.repositoryIdentities.find((x)=>x.agent==='loony-luna');write(path.join(f.slots['loony-luna'],'new-cache/attack.js'),'attack-two()');const second=run(f),b=second.repositoryIdentities.find((x)=>x.agent==='loony-luna');expectFinding(first,{failureClass:'UNCLASSIFIED_FILE',agent:'loony-luna',affectedPath:'new-cache/attack.js'});assert.notEqual(prior.digests.completeObservedTreeDigest,a.digests.completeObservedTreeDigest);assert.notEqual(a.digests.completeObservedTreeDigest,b.digests.completeObservedTreeDigest);assert.notEqual(before.topLevelIdentity.observationEnvelopeDigest,first.topLevelIdentity.observationEnvelopeDigest);assert.notEqual(first.topLevelIdentity.observationEnvelopeDigest,second.topLevelIdentity.observationEnvelopeDigest);}finally{clean(f);}});

for(const rel of ['.next/server/worker.js','.next/static/service-worker.js','coverage/index.html','coverage/runtime.js','dist/runtime.js.map','dist/launch','invented-cache/output.js'])test(`TRIO-001D generated/exclusion closure: ${rel} blocks when newly introduced`,()=>{const f=fixture();try{write(path.join(f.slots['loony-luna'],rel),rel.endsWith('.html')?'<script>attack()</script>':rel.endsWith('.map')?'{"sourcesContent":["attack()"]}':'#!/bin/sh\nattack\n',rel.endsWith('/launch')?0o755:0o644);expectFinding(run(f),{failureClass:'UNCLASSIFIED_FILE',agent:'loony-luna',affectedPath:rel});}finally{clean(f);}});

const pngSignature=Buffer.from([137,80,78,71,13,10,26,10]);
const pngChunk=(type,data=Buffer.alloc(0))=>{const head=Buffer.alloc(8),crc=Buffer.alloc(4);head.writeUInt32BE(data.length,0);head.write(type,4,'ascii');return Buffer.concat([head,data,crc]);};
const structuralPng=(width=1,height=1)=>{const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(width,0);ihdr.writeUInt32BE(height,4);ihdr[8]=8;ihdr[9]=2;return Buffer.concat([pngSignature,pngChunk('IHDR',ihdr),pngChunk('IEND')]);};
for(const [label,data] of [
  ['signature plus script',Buffer.concat([pngSignature,Buffer.from('<script>attack()</script>')])],
  ['valid structure plus trailing bytes',Buffer.concat([structuralPng(),Buffer.from('trailing')])],
  ['malformed chunk',Buffer.concat([pngSignature,Buffer.from([0,0,0,64]),Buffer.from('IHDR')])],
  ['truncated image',pngSignature],
  ['oversized dimensions',structuralPng(20000,20000)],
  ['SVG renamed as PNG',Buffer.from('<svg onload="attack()"></svg>')],
  ['MIME and extension disagreement',Buffer.from('GIF89a')]
])test(`TRIO-001D asset quarantine: ${label} blocks`,()=>{const f=fixture();try{for(const root of Object.values(f.slots))write(path.join(root,'peh-hedge-knight.png'),data);expectFinding(run(f),{failureClass:'CONTENT_VALIDATION',agent:'pehlichi',affectedPath:'peh-hedge-knight.png'});expectFinding(run(f),{failureClass:'QUARANTINED_DIVERGENCE',affectedPath:'peh-hedge-knight.png'});}finally{clean(f);}});

test('TRIO-001D human rendering encodes bidi, zero-width, controls, newlines, and delimiters',()=>{const f=fixture();try{const raw='spoof\u202e\u200b\n|=x.js';write(path.join(f.slots.pehlichi,raw),'attack()');const result=run(f),rendered=human(result),machine=JSON.stringify(result);assert.equal(result.status,'VERIFIER_OK_DIVERGENCE');for(const ch of ['\u202e','\u200b']){assert.equal(rendered.includes(ch),false);assert.equal(machine.includes(ch),false);}assert.equal(machine.includes('\n'),false);assert.match(rendered,/\\u\{202e\}/);assert.match(rendered,/\\u\{200b\}/);assert.match(rendered,/\\u\{a\}/);assert.match(rendered,/\\u\{7c\}/);assert.match(rendered,/\\u\{3d\}/);}finally{clean(f);}});

// ── Owner-scoped trees: the exemption buys absence, never silence ─────────────
test('owner-scoped: a tree present only in its declared owner reaches parity',()=>{const f=fixture();try{ownerScopedTree(f);const r=run(f);assert.equal(r.summary.verdict,'PARITY');assert.equal(r.summary.ownerScopedFiles,2);}finally{clean(f);}});
test('owner-scoped hostile: the same tree appearing in a second repository blocks',()=>{const f=fixture();try{const t=ownerScopedTree(f);write(path.join(f.slots['mad-ptah'],t.members[0]),'# private\n');expectFinding(run(f),{failureClass:'OWNER_SCOPE_VIOLATION',affectedPath:t.members[0]});}finally{clean(f);}});
test('owner-scoped hostile: absence from the declared owner blocks',()=>{const f=fixture();try{const t=ownerScopedTree(f);fs.rmSync(path.join(f.slots[t.owner],t.members[0]));expectFinding(run(f),{failureClass:'OWNER_SCOPE_ABSENT',affectedPath:t.members[0]});}finally{clean(f);}});
test('owner-scoped hostile: a governed file referencing the tree blocks',()=>{const f=fixture();try{const t=ownerScopedTree(f);write(path.join(f.slots[t.owner],'src/main.ts'),`export const p='${t.dir}/notes.md';\n`);expectBlocked(run(f),'OWNER_SCOPE_REFERENCED');}finally{clean(f);}});
test('owner-scoped hostile: naming the tree in the shared runtime closure blocks',()=>{const f=fixture();try{const t=ownerScopedTree(f);for(const root of Object.values(f.slots))write(path.join(root,'trio/runtime-closure.json'),JSON.stringify({governedCommon:[t.members[0]]}));expectBlocked(run(f),'OWNER_SCOPE_REACHABLE');}finally{clean(f);}});
test('owner-scoped hostile: a package script invoking the tree blocks',()=>{const f=fixture();try{const t=ownerScopedTree(f);const pkg=readStrictJson(path.join(f.slots[t.owner],'package.json'));pkg.scripts.demo=`bash ${t.dir}/run.sh`;write(path.join(f.slots[t.owner],'package.json'),JSON.stringify(pkg));expectBlocked(run(f),'OWNER_SCOPE_PACKAGE_HOOK');}finally{clean(f);}});
test('owner-scoped hostile: a service unit inside the tree blocks',()=>{const f=fixture();try{ownerScopedTree(f,{files:{'notes.md':'# private\n','agent.service':'[Service]\n'}});expectBlocked(run(f),'OWNER_SCOPE_ENTRYPOINT');}finally{clean(f);}});
test('owner-scoped hostile: an unacknowledged byte change blocks',()=>{const f=fixture();try{const t=ownerScopedTree(f);write(path.join(f.slots[t.owner],t.members[0]),'# quietly changed\n');expectBlocked(run(f),'OWNER_SCOPE_DIGEST');}finally{clean(f);}});
test('owner-scoped hostile: an unmeasured tree digest blocks',()=>{const f=fixture();try{ownerScopedTree(f,{acknowledge:false});expectBlocked(run(f),'OWNER_SCOPE_DIGEST');}finally{clean(f);}});
test('owner-scoped hostile: claiming production reachability or byte identity is refused',()=>{
  for(const override of [{productionReachable:true},{bytesMustMatch:true},{divergenceBlocking:true}]){
    const f=fixture();try{ownerScopedTree(f,{rule:override});expectBlocked(run(f),'OWNER_SCOPE_CONTRACT','MANIFEST_INVALID');}finally{clean(f);}
  }
});
test('owner-scoped hostile: an owner outside the three agents is refused by the schema',()=>{const f=fixture();try{ownerScopedTree(f,{rule:{owner:'nobody'}});expectBlocked(run(f),'SCHEMA_VALIDATION','SCHEMA_INVALID');}finally{clean(f);}});
test('owner-scoped hostile: owner/attestation/digest on a non-owner-scoped rule is refused',()=>{const f=fixture();try{f.manifest.rules.find((r)=>r.id==='source-runtime').owner='loony-luna';f.setManifest(f.manifest);expectBlocked(run(f),'OWNER_SCOPE_CONTRACT','MANIFEST_INVALID');}finally{clean(f);}});
test('owner-scoped hostile: an unknown file inside the owner tree is still fail-closed',()=>{const f=fixture();try{const t=ownerScopedTree(f);write(path.join(f.slots[t.owner],t.dir,'surprise.md'),'not enumerated\n');expectBlocked(run(f),'UNCLASSIFIED_FILE');}finally{clean(f);}});
