/**
 * Lab agent — public API.
 *
 * Each agent is independent: it owns its core runtime (src/core/) and depends
 * only on shared DATA stores (lab-store, lab-memory), never on another agent.
 * The runtime is byte-identical across the trio; the per-agent overlay is
 * personality + skills + branding (see src/profiles/agent.ts).
 *
 * The core surface is forwarded by name. It was `export * from "./core/index.js"`, and a star
 * re-export cannot be audited by reading it: it exports whatever the target exports, including
 * whatever the target starts exporting tomorrow. That is how `runtime/core/loop.ts` came to
 * re-export both below-admission executors into a second namespace, where the same
 * computed-property bypass would have reached them. Written out, this file's surface is a
 * decision somebody made rather than a consequence of one made elsewhere -- and the two
 * executors are absent from it by construction, not by the target's continued good behaviour.
 */
export {
  BridgeError,
  BridgeRegistry,
  CircuitBreaker,
  ContextCompressor,
  EventEmitter,
  GOVERNED_STATUS_PATH,
  HttpBridge,
  IterationBudget,
  LLAMACPP_RESPONSE_PROTOCOL,
  LlamaCppDriver,
  LlamaCppError,
  MIMO_RESPONSE_PROTOCOL,
  MimoDriver,
  MimoError,
  OLLAMA_RESPONSE_PROTOCOL,
  OllamaDriver,
  OllamaError,
  OperationalStatusUnreadable,
  OperationalWorkRefused,
  ReceiptStore,
  RetryPolicy,
  ScriptedDriver,
  ShadowWorkspace,
  SharedBudget,
  TokenMonitor,
  ToolError,
  UNATTENDED_ALLOWED_TOOLS,
  activeCapabilityList,
  admitNonWorkSurface,
  admitRunWork,
  admitWork,
  allCircuits,
  assertUnattendedStartup,
  bridgeRegistry,
  buildSystemPrompt,
  completionToAction,
  createBridgeReceiptSink,
  createStdoutSink,
  createToolRegistry,
  delegationDepthDenyReason,
  describeRefusal,
  formatEvent,
  getCircuit,
  isRetryable,
  isToolAllowedUnattended,
  isUsageReportingDriver,
  parseChatCompletion,
  readOperationalStatus,
  resolveInWorkspace,
  runAgent,
  runAgentInShadow,
  runtimeCapabilities,
  sleep,
  toProviderTools,
  toWireMessages,
  toolSpecs,
  unattendedToolDenyReason,
  verifyUnattendedSuccess,
  withRetry,
  type AdmissionDecision,
  type AdmissionRefusal,
  type AgentEvent,
  type AgentEventInput,
  type AgentProfile,
  type ApprovalCallback,
  type BridgeConfig,
  type BridgeHealth,
  type BridgeInfo,
  type BridgeReceipt,
  type BridgeReceiptInput,
  type BudgetStatus,
  type CircuitConfig,
  type CircuitState,
  type CircuitStatus,
  type CompressResult,
  type ContextCompressorOptions,
  type Driver,
  type DriverAction,
  type DriverContext,
  type EventMeta,
  type EventSink,
  type FetchLike,
  type GovernedExecRequest,
  type LlamaCppDriverOptions,
  type Message,
  type MimoDriverOptions,
  type NonWorkSurface,
  type OllamaDriverOptions,
  type OperationalAuthorization,
  type OperationalState,
  type OperationalStatus,
  type ParsedCompletion,
  type Phase,
  type Receipt,
  type ReceiptStoreOptions,
  type RefusalCode,
  type RetryConfig,
  type RunAgentInShadowOptions,
  type RunAgentOptions,
  type RunAgentResult,
  type RuntimeCapabilities,
  type RuntimeCapabilityInput,
  type ShadowRunResult,
  type TerminalReceipt,
  type TokenMonitorConfig,
  type TokenSummary,
  type TokenUsage,
  type ToolApprovalDecision,
  type ToolApprovalRequest,
  type ToolContext,
  type ToolDef,
  type ToolHandler,
  type ToolRegistry,
  type ToolResult,
  type ToolSpec,
  type UnattendedResult,
  type UnattendedToolContext,
  type UsageRecord,
  type UsageReportingDriver,
  type WorkCategory
} from './core/index.js';

export { agentProfile, agentToolNames } from "./profile.js";

export {
  bridgeToolSpecs,
  createBridgeToolHandlers,
} from "./tools/bridge-tools.js";
